### ISSUE TITLE
Share Names with Spaces

### ISSUE THREAD

**Issue by gskibum** [robperc/FinderSidebarEditor#1]
Is there a way of getting shares with spaces in the name to work? I can get shares without spaces in the names to work, but they don't work if there is a space in the name.

**Comment by robperc** [comment]
Can you share an example of the path you're trying to add and the errors (if any) you're getting when you try to add it?

**Comment by gskibum** [comment]
Here's what does work:
`sidebar.add("/Photography", uri="afp://server.domain.com")`

Here's what does not work:
`sidebar.add("/Client Files", uri="afp://server.domain.com")`
or
`sidebar.add("/Client\ Files", uri="afp://server.domain.com")`

The error:
`raise Exception('Error mounting url "%s": %s' % (share_path, output))
Exception: Error mounting url "afp://server.domain.com/Client Files": None
`

If I used the escaped version the error just shows as the escaped version is expressed.

**Comment by robperc** [comment]
Interesting. Thanks for the error info! Here's where the issue is in the code:

https://github.com/robperc/FinderSidebarEditor/blob/master/FinderSidebarEditor.py#L46

The **mount_share** function actually a chunk of code I borrowed from Mike Lynn. It looks like **NetFS.NetFSMountURLSync** has trouble mounting URLs with spaces in them. Have you tried URL encoding the space? (ex: space = %20) If that doesn't you can try pinging Mike Lynn (https://github.com/pudquick).

**Comment by gskibum** [comment]
(space = %20) totally did the trick.

Thank you!
